config/routes.rb
Rails.application.routes.draw do
  root 'guest_book#index'

  post   'guest_book/sign'
  delete 'guest_book/destroy/:id', to: 'guest_book#destroy', as: 'destroy'
  get    'guest_book/wipe',        to: 'guest_book#wipe',    as: 'wipe_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  validates :color, format: { with: /[0-9A-Fa-f]{6}/ }, allow_nil: true
  validates :name,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: /\A[a-zA-Z0-9 ]+\z/ }

  before_validation :add_color, on: :create
  after_initialize  :add_color if :new_record?

  before_validation :add_image, on: :create
  after_initialize  :add_image if :new_record?

  private

  def add_color
    return nil unless color.blank?

    self.color = ''
    3.times.each { self.color += '%02X' % Random.rand(0..255) }
  end

  def add_image
    return nil unless image_number.blank? || image_number.zero?

    self.image_number = Random.rand(0..100)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guest_book_controller.rb
class GuestBookController < ApplicationController
  GUEST_LIMIT = 200

  def index
    @guests = Guest.all.limit(50).order(created_at: :desc)
    @guest  = Guest.new if Guest.count < GUEST_LIMIT
  end

  def sign
    if Guest.count >= GUEST_LIMIT
      flash[:error] = 'Guest count too large'
      redirect_to(root_path)
    end

    @guest = Guest.new(permitted_params)
    if @guest.save
      flash[:success] = "#{@guest.name} created successfully"
    else
      flash[:error] = 'Sorry, something went wrong'
    end
    redirect_to(root_path)
  end

  def destroy
    @guest = Guest.find_by(id: params[:id])
    if @guest&.delete
      flash[:success] = 'Guest successfully removed'
    else
      flash[:error] = 'Guest could not be removed'
    end
    redirect_to(root_path)
  end

  def wipe
    Guest.destroy_all
    redirect_to(root_path)
  end

  private

  def permitted_params
    params.require(:guest).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_book_helper.rb
module GuestBookHelper
  FLICKR_PATH  = 'https://loremflickr.com'.freeze
  SEARCH_TERMS = 'animal,dog,cat'.freeze
  PICSUM_PATH  = 'https://picsum.photos'.freeze

  def avitar_image(seed: 0, width: 100, height: 160)
    picsum_image(seed: seed, width: width, height: height)
  end

  def picsum_image(seed: 0, width: 100, height: 160)
    location = safe_join([PICSUM_PATH, 'seed', seed, width, height], '/')
    image_tag(location, width: width, height: height, alt: 'Avitar')
  end

  def flicker_image(seed: 0, width: 100, height: 160)
    location = safe_join([FLICKR_PATH, width, height, SEARCH_TERMS], '/') + "?lock=#{seed}"
    image_tag(location, width: width, height: height, alt: 'Avitar')
  end
end

app/views/guest_book/_form.html.erb
<% return nil unless @guest.present? %>

<div class="col s12 m7">
  <div class="card horizontal">
    <div class="card-stacked">
      <div class="card-content">
        <h4>Sign the guest book</h4>

        <%= form_for(@guest, url: { action: "sign" }) do |f| %>
          <div class="form-group input-field col s12">
            <%= label(:category, :name) %>
            <%= f.text_field(:name, class: "form-control") %>
          </div>
          <button class="btn waves-effect waves-light <%= ChsHerokuDemo::COLOR_THEME %>" type="submit" name="action">Sign
            <i class="material-icons right">person_add</i>
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/guest_book/index.html.erb
<br />
<%= render "guest_book/form" %>

<a class="btn-floating btn-large waves-effect waves-light <%= ChsHerokuDemo::COLOR_THEME %> right" href="<%= wipe_book_path %>">
  <i class="material-icons">delete_sweep</i>
</a>
<h4>Guests</h4>
Total of <%= @guests.count %>

<% @guests.each do |guest| %>
  <div class="col s12 m7">
    <div class="card horizontal">
      <div class="card-image">
        <%= avitar_image(seed: guest.image_number, width: 150, height: 150) %>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">
            <%= guest.name %>
            <i class="material-icons" style="color: #<%= guest.color %> !important;">person</i>
          </span>
          <p></p>
        </div>
        <div class="card-action">
          <%= link_to("Remove",
                      destroy_path(guest),
                      method: :delete,
                      class: "#{ChsHerokuDemo::COLOR_THEME}-text text-darken-2") %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_alert.html.erb
<div class="container">
  <% flash.each do |message_type, message| %>
    <% card_color = (message_type == 'error' || message_type == 'alert' || message_type == 'danger') ? 'red' : 'green' %>

    <div class="col s12 m7">
      <div class="card horizontal">
        <div class="card-stacked  <%= card_color %> lighten-3">
          <div class="card-content black-text">
            <p><%= message %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer <%= ChsHerokuDemo::COLOR_THEME %> darken-1" style="padding-bottom: 8px;">
  <div class="container">
    <span class="white-text">
      © 2020 <a href="https://www.meetup.com/CHS-Amazon-Web-Services" target="_blank" class="white-text">Charleston Aws Meetup</a>
    </span>
    <span class="right white-text">
      Source on <a href="https://github.com/awsmeetupdemo/chs-heroku-demo" target="_blank" class="white-text">Github</a>
    </span>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="<%= ChsHerokuDemo::COLOR_THEME %> darken-1">
  <div class="container">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Heroku Demo</a>
      <span class="right">Sample application power by Heroku</span>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chs Heroku Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main>
      <%= render "layouts/alert" if flash.present? %>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>